language: go
go: 1.12.x

services:
  - docker

install:
  - make build
  - make start

script:
  - docker ps | grep -q golang-daemon-starter

deploy:
  provider: script
  script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  on:
    branch: master
